// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using PhoneShop.Models;
using System;

namespace PhoneShop.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20170910103401_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("PhoneShop.Models.Pictures", b =>
                {
                    b.Property<string>("PicturesId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Large");

                    b.Property<string>("Small");

                    b.HasKey("PicturesId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("PhoneShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("PictureId");

                    b.Property<string>("PicturesId");

                    b.Property<float>("Price");

                    b.HasKey("ProductId");

                    b.HasIndex("PicturesId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PhoneShop.Models.Specification", b =>
                {
                    b.Property<int>("SpecificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProductId");

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("SpecificationId");

                    b.HasIndex("ProductId");

                    b.ToTable("Specification");
                });

            modelBuilder.Entity("PhoneShop.Models.Product", b =>
                {
                    b.HasOne("PhoneShop.Models.Pictures", "Pictures")
                        .WithMany()
                        .HasForeignKey("PicturesId");
                });

            modelBuilder.Entity("PhoneShop.Models.Specification", b =>
                {
                    b.HasOne("PhoneShop.Models.Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
